directories:
  output: dist
  buildResources: build

files: build/*.js

protonNodeVersion: current

win:
  # icon: ./img/icons/win/icon.ico
  target:
    - nsis
    - zip
  publish:
    - github

mac:
  # icon: ./img/icons/mac/icon.icns
  category: public.app-category.utility
  target:
    - dmg
    - zip
  publish:
    - github

nsis:
  allowToChangeInstallationDirectory: true
  oneClick: false
  perMachine: true